/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.text.NumberFormat;
import java.util.Locale;
import modelo.BalanceGeneral;
import modelo.LibroMayor;
/**
 *
 * @author dsm
 */
public class BalanceGeneralGUI extends javax.swing.JFrame {

    BalanceGeneral bG;
    /**
     * Creates new form BalanceGeneralGUI
     */
    public BalanceGeneralGUI(LibroMayor libroMayor) {
        initComponents();
        bG = new BalanceGeneral(libroMayor,"SYSTEMCOM S.A.S.");
        NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.US);
        
        if(libroMayor.isClose())
        {
            titleLabel.setText(bG.titulo());
            totalActivosLabel.setText("TOTAL ACTIVOS = "+nf.format(bG.totalActivos));
            activosArea.setText(bG.activos());
            totalPasivosLabel.setText("TOTAL PASIVOS = "+nf.format(bG.totalPasivos));
            pasivoArea.setText(bG.pasivos());
            totalPatrimonio.setText("TOTAL PATRIMONIO = "+nf.format(bG.totalPatrimonio));
            patrimonioArea.setText(bG.patrimonio());
            double totalPasivoActivo = bG.totalPasivos+bG.totalPatrimonio;
            totalesLabel.setText("TOTAL ACTIVOS = "+nf.format(bG.totalActivos)+"              PASIVO + PATRIMONIO = "+nf.format(totalPasivoActivo));
        }else{
            activosArea.setText("LIBRO MAYOR NO ESTA CERRADO, POR FAVOR CIERRELO PARA GENERAR EL BALANCE GENERAL");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        totalActivosLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activosArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pasivoArea = new javax.swing.JTextArea();
        totalPasivosLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        patrimonioArea = new javax.swing.JTextArea();
        totalPatrimonio = new javax.swing.JLabel();
        totalesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 60, 9));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BALANCE GENERAL");

        titleLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(244, 66, 14));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        totalActivosLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalActivosLabel.setForeground(new java.awt.Color(10, 0, 0));
        totalActivosLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        activosArea.setColumns(20);
        activosArea.setRows(5);
        jScrollPane1.setViewportView(activosArea);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(10, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ACTIVOS");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(10, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PASIVOS");

        pasivoArea.setColumns(20);
        pasivoArea.setRows(5);
        jScrollPane2.setViewportView(pasivoArea);

        totalPasivosLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalPasivosLabel.setForeground(new java.awt.Color(10, 0, 0));
        totalPasivosLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(10, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PATRIMONIO");

        patrimonioArea.setColumns(20);
        patrimonioArea.setRows(5);
        jScrollPane3.setViewportView(patrimonioArea);

        totalPatrimonio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalPatrimonio.setForeground(new java.awt.Color(10, 0, 0));

        totalesLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        totalesLabel.setForeground(new java.awt.Color(229, 56, 14));
        totalesLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalActivosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalPatrimonio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(totalPasivosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                            .addComponent(jScrollPane3))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPasivosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalActivosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(totalesLabel)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea activosArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea pasivoArea;
    private javax.swing.JTextArea patrimonioArea;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel totalActivosLabel;
    private javax.swing.JLabel totalPasivosLabel;
    private javax.swing.JLabel totalPatrimonio;
    private javax.swing.JLabel totalesLabel;
    // End of variables declaration//GEN-END:variables
}
