/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import modelo.EstadoDeResultados;
import modelo.LibroMayor;
/**
 *
 * @author dsm
 */
@SuppressWarnings("serial")
public class EdRGUI extends javax.swing.JFrame {

    EstadoDeResultados eDR;
    /**
     * Creates new form EdRGUI
     * @param libroMayor 
     */
    public EdRGUI(LibroMayor libroMayor) {
        initComponents();
        eDR = new EstadoDeResultados(libroMayor,"SYSTEMCOM S.A.S.");
        if(libroMayor.isClose()){
            eDR.ejecutar();
            estadoArea.setText(eDR.toSting());
        }else{
            estadoArea.setText("DEBE CERRAR PRIMERO EL LIBRO PARA VER EL ESTADO DE RESULTADOS");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        estadoArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 58, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTADO DE RESULTADOS");

        estadoArea.setColumns(20);
        estadoArea.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        estadoArea.setRows(5);
        jScrollPane1.setViewportView(estadoArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea estadoArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
